<?xml version="1.0" encoding="utf-8"?><Database Name="SUPPLIER_INDICATOR" Class="dbSupplierIndicatorDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=W08R2-UPDATE\RYBACK;Initial Catalog=SUPPLIER_INDICATORDev;Integrated Security=True" SettingsObjectName="Supplier_Indicator.My.MySettings" SettingsPropertyName="SUPPLIER_INDICATORDevConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="SERTA.T_SUP_ASSESSMENT_SUA" Member="SUP_ASSESSMENT_SERTA" AccessModifier="Internal">
    <Type Name="SUP_ASSESSMENT_SERTA" AccessModifier="Internal">
      <Column Name="SUA_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SUP_ID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="SUA_QUARTER" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="SUA_FORM" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="SUA_INDICE_PPM_VALUE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SUA_INDICE_PPM_POINT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SUA_SIN_NB_VALUE" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_SIN_NB_POINT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SUA_CUSTOMER_CLAIM_NB_VALUE" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_CUSTOMER_CLAIM_NB_POINT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SUA_ACTION_PLAN_REACTIVITY_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_BONUS_500_PPM_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_LOGISTIC_RATE_TARGET_95_VALUE" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_LOGISTIC_RATE_TARGET_95_POINT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SUA_FLEXIBILITY_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_DELIVERY_DELAYS_LEVEL_VALUE" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_DELIVERY_DELAYS_LEVEL_POINT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SUA_DELIVERY_QUALITY_VALUE" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_DELIVERY_QUALITY_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_PRICE_COMPETITIVENESS_VALUE" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_PRICE_COMPETITIVENESS_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_IMPROVMENT_PLAN_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_BUSINESS_RELATIONSHIP_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_FINANCIAL_SITUATION_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_OFFERS_REACTIVITY_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_TECHNICAL_ANSWER_QUALITY_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_ISO_CERTFICATION_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_COMMENT" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SUA_COMMENT_DETAIL" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SUA_COMMENT_CLASSIFICATION" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SUA_COMMENT_GLOBAL" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SUA_TOTAL_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_TREND" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="PNS.T_SUP_ASSESSMENT_SUA" Member="SUP_ASSESSMENT_PNS" AccessModifier="Internal">
    <Type Name="SUP_ASSESSMENT_PNS" AccessModifier="Internal">
      <Column Name="SUA_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SUP_ID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="SUA_QUARTER" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="SUA_INDICE_PPM_VALUE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SUA_INDICE_PPM_POINT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SUA_SIN_NB_VALUE" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_SIN_NB_POINT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SUA_CUSTOMER_CLAIM_NB_VALUE" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_CUSTOMER_CLAIM_NB_POINT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SUA_ACTION_PLAN_REACTIVITY_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_BONUS_500_PPM_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_LOGISTIC_RATE_TARGET_95_VALUE" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_LOGISTIC_RATE_TARGET_95_POINT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SUA_FLEXIBILITY_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_DELIVERY_DELAYS_LEVEL_VALUE" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_DELIVERY_DELAYS_LEVEL_POINT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SUA_DELIVERY_QUALITY_VALUE" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_DELIVERY_QUALITY_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_PRICE_COMPETITIVENESS_VALUE" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_PRICE_COMPETITIVENESS_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_IMPROVMENT_PLAN_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_BUSINESS_RELATIONSHIP_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_FINANCIAL_SITUATION_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_OFFERS_REACTIVITY_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_TECHNICAL_ANSWER_QUALITY_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_ISO_CERTFICATION_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_COMMENT" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SUA_COMMENT_DETAIL" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SUA_COMMENT_CLASSIFICATION" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SUA_COMMENT_GLOBAL" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SUA_TOTAL_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_TREND" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="COMMON.T_SUP_ASSESSMENT_SUA" Member="SUP_ASSESSMENT_COMMUN" AccessModifier="Internal">
    <Type Name="SUP_ASSESSMENT_COMMUN" AccessModifier="Internal">
      <Column Name="SUA_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SUP_ID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="SUA_QUARTER" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="SUA_FORM" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="SUA_INDICE_PPM_VALUE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SUA_INDICE_PPM_POINT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SUA_SIN_NB_VALUE" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_SIN_NB_POINT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SUA_CUSTOMER_CLAIM_NB_VALUE" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_CUSTOMER_CLAIM_NB_POINT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SUA_ACTION_PLAN_REACTIVITY_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_BONUS_500_PPM_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_LOGISTIC_RATE_TARGET_95_VALUE" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_LOGISTIC_RATE_TARGET_95_POINT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SUA_FLEXIBILITY_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_DELIVERY_DELAYS_LEVEL_VALUE" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_DELIVERY_DELAYS_LEVEL_POINT" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SUA_DELIVERY_QUALITY_VALUE" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_DELIVERY_QUALITY_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_PRICE_COMPETITIVENESS_VALUE" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_PRICE_COMPETITIVENESS_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_IMPROVMENT_PLAN_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_BUSINESS_RELATIONSHIP_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_FINANCIAL_SITUATION_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_OFFERS_REACTIVITY_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_TECHNICAL_ANSWER_QUALITY_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_ISO_CERTFICATION_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_COMMENT" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SUA_COMMENT_DETAIL" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SUA_COMMENT_CLASSIFICATION" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SUA_COMMENT_GLOBAL" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SUA_TOTAL_POINT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUA_TREND" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="COMMON.P_ASSESSMENT_SUPPLIER_LIST" Method="P_Supplier_list_Commun" AccessModifier="Internal">
    <ElementType Name="P_ASSESSMENT_SUPPLIER_LISTResult">
      <Column Name="SUP_ID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="SUP_NAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SUP_CODE" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="PNS.P_SUPPLIER_LIST" Method="P_Supplier_list_PNS" AccessModifier="Internal">
    <ElementType Name="P_SUPPLIER_LISTResult">
      <Column Name="SUP_ID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="SSC_ID" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUPPLIER_NAME" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="SERTA.P_SUPPLIER_LIST" Method="P_Supplier_list_SERTA" AccessModifier="Internal">
    <ElementType Name="P_SUPPLIER_LISTResult1">
      <Column Name="SUP_ID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="SSC_ID" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="SUP_NAME" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="COMMON.P_ASSESSMENT_VALUES" Method="P_Assessment_Values_Commun" AccessModifier="Internal">
    <Parameter Name="SUP_ID" Parameter="sUP_ID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="QUARTER" Parameter="qUARTER" Type="System.String" DbType="Char(3)" />
    <ElementType Name="P_ASSESSMENT_VALUESResult">
      <Column Name="PPM_PNS" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="QNC_COUNT_PNS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CUSTOMER_CLAIM_COUNT_PNS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LNC_COUNT_PNS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOGISTIC_RATE_PNS" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="DELAYS_UP_TO_10_DAYS_RATE_PNS" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="PPM_SERTA" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="QNC_COUNT_SERTA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CUSTOMER_CLAIM_COUNT_SERTA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LNC_COUNT_SERTA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOGISTIC_RATE_SERTA" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="DELAYS_UP_TO_10_DAYS_RATE_SERTA" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="PPM_GROUP" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="QNC_COUNT_GROUP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CUSTOMER_CLAIM_COUNT_GROUP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LNC_COUNT_GROUP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOGISTIC_RATE_GROUP" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="DELAYS_UP_TO_10_DAYS_RATE_GROUP" Type="System.Single" DbType="Real" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="PNS.P_ASSESSMENT_VALUES" Method="P_Assessment_Values_PNS" AccessModifier="Internal">
    <Parameter Name="SUP_ID" Parameter="sUP_ID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="QUARTER" Parameter="qUARTER" Type="System.String" DbType="Char(3)" />
    <ElementType Name="P_ASSESSMENT_VALUESResult1">
      <Column Name="PPM" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="QNC_COUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CUSTOMER_CLAIM_COUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LNC_COUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOGISTIC_RATE" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="DELAYS_UP_TO_10_DAYS_RATE" Type="System.Single" DbType="Real" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="SERTA.P_ASSESSMENT_VALUES" Method="P_Assessment_Values_SERTA" AccessModifier="Internal">
    <Parameter Name="SUP_ID" Parameter="sUP_ID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="QUARTER" Parameter="qUARTER" Type="System.String" DbType="Char(3)" />
    <ElementType Name="P_ASSESSMENT_VALUESResult2">
      <Column Name="PPM" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="QNC_COUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CUSTOMER_CLAIM_COUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LNC_COUNT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOGISTIC_RATE" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="DELAYS_UP_TO_10_DAYS_RATE" Type="System.Single" DbType="Real" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="COMMON.P_CATEGORY_LIST" Method="P_CATEGORY_LIST" AccessModifier="Internal">
    <ElementType Name="P_CATEGORY_LISTResult">
      <Column Name="SCA_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SCA_DESCRIPTION" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="COMMON.P_SUB_CATEGORY_LIST" Method="P_SUB_CATEGORY_LIST" AccessModifier="Internal">
    <ElementType Name="P_SUB_CATEGORY_LISTResult">
      <Column Name="SSC_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SCA_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SSC_DESCRIPTION" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>